### ISSUE TITLE
Suggestion: Command line options for batch processing? 

### ISSUE THREAD

**Issue by medp7060** [cqwlxxl/klm-release#1]
A very useful tool, thanks.

Is it possible to add command lines support for the tools, including KRC <=> KRCD and KRC => other formats?

This can be useful to process a large number of files.

**Comment by cqwlxxl** [comment]
I'm glad this software can help you!
Subsequent updates will consider adding this feature when I have time.

**Comment by cqwlxxl** [comment]
> A very useful tool, thanks.
> 
> Is it possible to add command lines support for the tools, including KRC <=> KRCD and KRC => other formats?
> 
> This can be useful to process a large number of files.

This feature is supported in version 1.0.3.0
