### ISSUE TITLE
闪退如何查看运行log

### ISSUE THREAD

**Issue by luoyanghero** [cqwlxxl/klm-release#11]
klm1.0.3.8.
使用krc转换为lrc时，批量处理时，有些krc不支持，程序会闪退，有没有保存的log文件，查看具体的信息,
找到的一个不支持krc文件，上传可以分析。
[Uploading 赵鹏 - 女人花-974e2887b139531fe4aee5f5221778e6.krc…]()

**Comment by luoyanghero** [comment]
附件我上传到百度云吧
通过百度网盘分享的文件：赵鹏 - 女人花-974e2887b139531fe4aee5f522...
链接：https://pan.baidu.com/s/1I-2rZWeNaIiHC6uMYpzhWA 
提取码：8lsb

**Comment by luoyanghero** [comment]
还有加了封面图片的mp3也播放不了。
我整理了一下，一起放这里。

**Comment by luoyanghero** [comment]
通过百度网盘分享的文件：KuGou_lyrics_debug
链接：https://pan.baidu.com/s/1zgXF5NfJree_8gQ4_gg6AQ 
提取码：zeia

**Comment by cqwlxxl** [comment]
等有空了再看吧

**Comment by cqwlxxl** [comment]
程序暂时没有添加log相关功能

**Comment by cqwlxxl** [comment]
分析结论：本程序目前不存在描述所存在的缺陷。两个krc格式内容均存在问题，mp3能正常播放。

1. 赵鹏 - 女人花-974e2887b139531fe4aee5f5221778e6.krc
![image](https://github.com/user-attachments/assets/8d3438d0-fc9a-4679-9076-9e2fccfcb4f6)
如上图，krc中存在非法空行，应该是制作者在制作后续中，单独编辑并删除了那一行出现的问题。
此情况可以通过软件中的【修改】=>【LRC->KRCD】手动删除该空行，然后再将修改后的KRCD通过【KRCD->KRC】保存成KRC，再转换。
后续本程序可能会处理KRC中存在异常空行的情况。

2. 北京的冬天-9007d73aa879b2a5ce7fa220ef8a1956.krc
![image](https://github.com/user-attachments/assets/cb2496ea-a642-45b6-9c4b-d11a3a11bfa1)
如上图，krc中依然存在非法行，第二个框中的参数应该是大于0的整数，这里是负数，所以此krc依然是错误的。
针对此种错误，后续程序不会作相关异常处理。
当然你依然可以用上述转换成krcd手动修正为正常的情况，在还原成krc进行转换。

3. Emma Re、EmmaRe - 呐喊.mp3
经测试，音乐正常播放。
程序在首次打开时提示过需要安装LAVFilters，猜测你不能正常播放的原因是没有安装LAVFilters解码器。
请安装后重试。

**Comment by luoyanghero** [comment]
感谢分析。
这些krc是以前的老文件，估计不规范。
LAVFilter确实没有安装。
