### ISSUE TITLE
能够添加".精准lrc"(foobar2000 0.5x)格式转换成.krc格式吗？

### ISSUE THREAD

**Issue by medp7060** [cqwlxxl/klm-release#2]
谢谢发布v1.0.3.0, 真是越来越好用了。

能够添加".精准lrc"(foobar2000 0.5x)格式转换成.krc格式吗？这样就可以实现多格式相互转换了。目前所有的转换是单向的，不能相互转换。而且，网上也没有发现其它应用可以把精准lrc转换成.krc格式。

**Comment by cqwlxxl** [comment]
下个版本会考虑现有格式互转的功能，等我有空余时间再去写吧

**Comment by cqwlxxl** [comment]
这个功能在1.0.3.1版本中已经实现了

**Comment by medp7060** [comment]
太好 了，谢谢您！
________________________________
