### ISSUE TITLE
请求支持明文krc格式支持

### ISSUE THREAD

**Issue by manamikk** [cqwlxxl/klm-release#3]
请求支持明文的krc文件，歌词来自汽水音乐，我看是明文的时间戳，但是作者的软件不支持当前格式，示例如下
![image](https://github.com/cqwlxxl/klm-release/assets/39846506/dfac1a26-7527-41a6-871e-1983e9f5bb52)
[The Best Of alan (阿兰出道十五周年精选集).zip](https://github.com/cqwlxxl/klm-release/files/13546035/The.Best.Of.alan.zip)

**Comment by cqwlxxl** [comment]
### 图中未编码krc文本获取
未编码的krc可以在【修改】->【拖入KRC】->【KRC->KRCD】中获得，这个很早就有了的，将后缀krcd改成krc即可。
如图所示：
![图片](https://github.com/cqwlxxl/klm-release/assets/90250048/78158d53-648a-411d-8610-2262099e1c46)

### 图中精准lrc获取
图中所示的精准lrc是foobar插件ESLyric 0.3.x版本的格式，可以在【转换】->【拖入krc】->【输入格式：lrc精准歌词(foobar ESLyric 0.3.x)】->【转换】得到。
如图所示：
![图片](https://github.com/cqwlxxl/klm-release/assets/90250048/50952563-4f59-4b13-bb14-63b20e8f98b6)

**Comment by manamikk** [comment]
我当前后缀文件名字就是krc，使用的命令如下，会有日志打印但是不会有文件转换，`D:\soft\klm\klm.exe -krc -elrc1-srt +sh "E:\The Best Of alan (阿兰出道十五周年精选集)"`
![image](https://github.com/cqwlxxl/klm-release/assets/39846506/bef3bf2f-30c5-4292-bf1a-f27714504730)

**Comment by manamikk** [comment]
> ### 图中未编码krc文本获取
> 未编码的krc可以在【修改】->【拖入KRC】->【KRC->KRCD】中获得，这个很早就有了的，将后缀krcd改成krc即可。 如图所示： ![图片](https://private-user-images.githubusercontent.com/90250048/287883373-78158d53-648a-411d-8610-2262099e1c46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTQ2MjIsIm5iZiI6MTcwMjIxNDMyMiwicGF0aCI6Ii85MDI1MDA0OC8yODc4ODMzNzMtNzgxNThkNTMtNjQ4YS00MTFkLTg2MTAtMjI2MjA5OWUxYzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEzMTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZWM4MGY2ZGVjZDVjNzZiNGQxNDM5NDU3ZGZhOTZkY2I5ZTdhMDc1OGI1Y2IxMGFhYTBiMmNmNTZiY2UzMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GetWhqfDwxbA4aEwCWsrfnz3xduK9e0d7dVX-1oZL4U)
> 
> ### 图中精准lrc获取
> 图中所示的精准lrc是foobar插件ESLyric 0.3.x版本的格式，可以在【转换】->【拖入krc】->【输入格式：lrc精准歌词(foobar ESLyric 0.3.x)】->【转换】得到。 如图所示： ![图片](https://private-user-images.githubusercontent.com/90250048/287883800-50952563-4f59-4b13-bb14-63b20e8f98b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTQ2MjIsIm5iZiI6MTcwMjIxNDMyMiwicGF0aCI6Ii85MDI1MDA0OC8yODc4ODM4MDAtNTA5NTI1NjMtNGY1OS00YjEzLWJiMTQtNjNiMjBlOGY5OGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEzMTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MDc5YTE2NjAxZWZhY2ZlYTQxMmQxM2ZiZmE4OTYyNDJlZjYxYWQ2N2YyNDEwMzMyNWQ1YTEwZWVkODc0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5aLaMXHLgiyRDuAaZ_wF2Ci7L6s30ueCWYBHit-YWG8)

我当前后缀文件名字就是krc，使用的命令如下，会有日志打印但是不会有文件转换，`D:\soft\klm\klm.exe -krc -elrc1-srt +sh "E:\The Best Of alan (阿兰出道十五周年精选集)"`
![image](https://github.com/cqwlxxl/klm-release/assets/39846506/bef3bf2f-30c5-4292-bf1a-f27714504730)

**Comment by cqwlxxl** [comment]
我大概懂你的意思了，你这个后缀名是krc，但实际并不是标准的krc格式，正常的krc格式是加密过的，你使用解密后的文档当做是krc肯定不行。
你这个krc文件实际上相当于我前面提到的krcd，所以你如果需要将这个解密后的krc文本转换成其他格式的话，可以先将后缀名改成krcd，然后用到下图中的krcd转krc，然后将真正的krc转换成其他格式即可。
![图片](https://github.com/cqwlxxl/klm-release/assets/90250048/ceaace13-fc47-4a6b-901f-f97412e9e1c7)

**Comment by manamikk** [comment]
> D:\soft\klm\klm.exe -krc -elrc1-srt +sh "E:\The Best Of alan (阿兰出道十五周年精选集)"

请问是否有使用命令调用的方法呢，打开软件操作的话要点几次才能完成这个操作

**Comment by cqwlxxl** [comment]
暂时不会加了
