### ISSUE TITLE
文件夹内数量过多会死机

### ISSUE THREAD

**Issue by laughtLOOL** [cqwlxxl/klm-release#5]
![image](https://github.com/cqwlxxl/klm-release/assets/83571492/d504f792-98c0-4b78-b994-c438a1615f66)
请看文件夹项目
![image](https://github.com/cqwlxxl/klm-release/assets/83571492/fc3c9aa6-3372-4b91-9ad8-9a4eea499554)
但我c尝试这样批量转换歌词时,会闪退,压力测试不过关

**Comment by laughtLOOL** [comment]
由于有些是标准逐行有些是eslyric的格式,如果能加上自动识别或者说只转换0.3其他的不转换跳过的逻辑就好了

**Comment by cqwlxxl** [comment]
软件自身会区分普通lrc、0.3.x版本lrc和0.5.x版本的lrc的，如你图中选择的是0.3.x是会跳过其他两种lrc的，你说的闪退应该是软件转换的过程中界面会卡死吧，因为软件转换过程中没有去更新界面响应，一次性转换的文件或者文件夹过多，本身就会很耗时，比如删选文件后缀，如果是lrc还要对每个lrc的内容进行判断以区分是哪个版本的lrc，所以点击转换后耐心等待即可。
目前没有打算写更新界面的逻辑。

**Comment by cqwlxxl** [comment]
软件自身会区分普通lrc、0.3.x版本lrc和0.5.x版本的lrc的，如你图中选择的是0.3.x是会跳过其他两种lrc的，你说的闪退应该是软件转换的过程中界面会卡死吧，因为软件转换过程中没有去更新界面响应，一次性转换的文件或者文件夹过多，本身就会很耗时，比如扫描所有文件文件夹、筛选文件后缀、如果是lrc还要对每个lrc的内容进行判断以区分是哪个版本的lrc，所以点击转换后耐心等待即可。
目前没有打算写更新界面的逻辑。

**Comment by laughtLOOL** [comment]
就是文件夹内有多种格式的,主要就是lrc和0.3版本2种,然后数量大概几千个,就是他会直接退出而不是停在那个位置未响应,不知道怎么个搞法,我更希望他是卡在哪里证明还在运行,而不是直接退出

**Comment by laughtLOOL** [comment]
![image](https://github.com/cqwlxxl/klm-release/assets/83571492/7edf7762-3ac2-4a13-b7e7-d75ad2b30c3d)
我试过在沙盒中运行,但是效果是一样的,有没有崩溃记录呢,可以发给你看看,就是开始转换,然后卡住,就闪退了

**Comment by laughtLOOL** [comment]
但是一点一点转是可以的,但是之前屯的歌词很多,要一点点搞好肝啊

**Comment by laughtLOOL** [comment]
也不用更新逻辑,现在的情况下好像是还在检索的时候就崩溃了, 由于之前屯歌的时候没有办法,找不到像这种转换软件,网易云的格式都是0.3的那种,在播放器根本读不出来我哭死

**Comment by laughtLOOL** [comment]
[歌词.zip]

老哥自己也可以试一下

**Comment by cqwlxxl** [comment]
问题已经在新版本1.0.3.6中解决了
