### ISSUE TITLE
错误识别lrc

### ISSUE THREAD

**Issue by laughtLOOL** [cqwlxxl/klm-release#6]
![image](https://github.com/cqwlxxl/klm-release/assets/83571492/656cf133-9bf3-4aeb-b8f0-7a92f36498f2)
作者,真不好意思了, as you can see

1036版本有些会漏识别lrc为标准逐行歌词

**Comment by laughtLOOL** [comment]
绷不住了额, 0.5就正常, 0.3不被识别
![image](https://github.com/cqwlxxl/klm-release/assets/83571492/29eb4c99-f995-47e9-8309-b87b1c0da853)

**Comment by laughtLOOL** [comment]
帮助作者测试bug,我义不容辞哈哈哈,感谢作者支持修复问题

**Comment by cqwlxxl** [comment]
正则表达式错误，已在版本1.0.3.7中修正
