### ISSUE TITLE
把LRC文件转换为其他格式的文件时，得到的文件是空白的。

### ISSUE THREAD

**Issue by naomoji** [cqwlxxl/klm-release#7]
使用的是1.0.3.8版本。转换LRC文件时，提示转换成功，但输出文件是空白的。以lrc转srt为例：
![1](https://github.com/user-attachments/assets/e3c6af31-f9c8-4525-acc5-a80496ece141)
![2](https://github.com/user-attachments/assets/787450fd-9455-41d3-9cbe-863c6a2ee399)
我测试了一下，发现当lrc的时间戳为[mm:ss.xxx]，即毫秒数为3位数时，就会出现这个bug。
时间戳为[mm:ss.xx]时，是可以转换的。
![3](https://github.com/user-attachments/assets/37ea8047-7b37-46bc-ba2e-17ff3e1ce3af)
![4](https://github.com/user-attachments/assets/04f67dad-9a2c-4b5d-b189-4c7026ce15f8)

**Comment by cqwlxxl** [comment]
非标准LRC(第三方音乐软件或个人自定义格式的)在本软件中不会作支持，标准的普通LRC时间戳是[mm:ss.zz]，只有两位标识毫秒数，即zz = zz*10 ms。
所以标准的LRC并未精确到ms级别，而是只精确到了10ms级别。

暂未打算对时间戳为[mm:ss.zzz]的非标准LRC作支持。

LRC作为一种歌词格式，本身已经有了标准的格式。很多个人或第三方的音乐软件会在此基础上作很多扩充，然而后缀名又不改成其他格式，因为格式混乱，不好统一，所以并没有去处理这些混杂格式的打算。

**Comment by naomoji** [comment]
谢谢，知道了。
