### ISSUE TITLE
LRC转SRT时，输出的SRT文件的时间戳不正确。

### ISSUE THREAD

**Issue by naomoji** [cqwlxxl/klm-release#8]
使用的是1.0.3.8版本。某种排版的LRC转SRT时，在输出的SRT文件里，某些语句的开始时间和结束时间相同。LRC和SRT对比如下图所示。
![1](https://github.com/user-attachments/assets/624ebb3d-121a-4401-a637-461c9569d5ba)
在LRC里，日文在上、中文在下时，则在转换出来的SRT里，中文的时间戳出错。
如果LRC里，中文在上、日文在下时，则在SRT里，日文的时间戳出错。
![2](https://github.com/user-attachments/assets/8f53727c-4328-44e5-997c-e6e2c8521bba)
SRT第一句的时间戳总是错的，无论LRC里中文在上在下。

**Comment by cqwlxxl** [comment]
软件只会支持标准的LRC，第三方定制的非标准化格式的LRC不会去作支持。
标准的LRC时间戳不会有重复的，语句相同可以重复，比如：
[00:00.00]A
[00:01.20]B
[00:02.30][00:03.55]C
[00:03.12]D
